# Generated by Django 3.2.8 on 2021-12-31 08:22

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20211125_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.IntegerField(choices=[(1, 'ادبیات'), (2, 'اسطوره\u200cای'), (3, 'اقتصاد'), (4, 'باستان\u200cشناسی'), (5, 'تاریخ'), (6, 'خاطره\u200cنویسی'), (7, 'رمان'), (8, 'داستان کوتاه'), (9, 'عرفان'), (10, 'دین'), (11, 'روان\u200cشناسی'), (14, 'جامعه\u200cشناسی'), (15, 'علوم\u200cانسانی'), (16, 'پزشکی'), (17, 'فلسفه'), (18, 'کودک و نوجوان'), (19, 'گزارش\u200cنویسی'), (20, 'مصاحبه'), (21, 'مقاله'), (22, 'موسیقی'), (23, 'هنر'), (24, 'سایر')], verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True, verbose_name='موقعیت جغرافیایی'),
        ),
    ]
