# Generated by Django 3.2.8 on 2021-11-04 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterPerception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perception', models.TextField(verbose_name='ادراک')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.theater', verbose_name='تئاتر')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='نمایه کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SongPerception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perception', models.TextField(verbose_name='ادراک')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.song', verbose_name='ترانه')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='نمایه کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoviePerception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perception', models.TextField(verbose_name='ادراک')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.movie', verbose_name='فیلم')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='نمایه کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JourneyPerception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perception', models.TextField(verbose_name='ادراک')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.journey', verbose_name='سفر')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='نمایه کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookPerception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perception', models.TextField(verbose_name='ادراک')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.book', verbose_name='کتاب')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='نمایه کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
