# Generated by Django 3.2.8 on 2021-11-04 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='تلفن همراه/Mobile')),
                ('gender', models.IntegerField(choices=[(2, 'زن/Female'), (3, 'سایر/Other'), (1, 'مرد/Male')], verbose_name='جنسیت/Gender')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد/Birth date')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور/County')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر/City')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users/profile_images', verbose_name='تصویر/Image')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='اعتبار/Credit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری/username')),
            ],
            options={
                'verbose_name': 'نمایه کاربری',
                'verbose_name_plural': 'نمایه کاربری',
            },
        ),
    ]
