# Generated by Django 3.2.8 on 2021-11-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(3, 'سایر/Other'), (1, 'مرد/Male'), (2, 'زن/Female')], verbose_name='جنسیت/Gender'),
        ),
    ]
