# Generated by Django 3.2.8 on 2021-11-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'مرد/Male'), (3, 'سایر/Other'), (2, 'زن/Female')], verbose_name='جنسیت/Gender'),
        ),
    ]
